name: CI by Kateryna
on:
  pull_request:
    branches:
      - main
env:
  GITHUB_ACTIONS_NAME: Python_app
jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: |
          echo "Hello World!"
          echo "Workflow started by ${{ github.actor }}"
          echo "${{ env.GITHUB_ACTIONS_NAME }}"
          echo "Branch: ${{ github.ref }} and repo: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
